version: "3.8"

services:
  db:
    image: postgres:14
    expose:
      - 5432
    environment:
      - POSTGRES_DB=twfactor
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password@1
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [CMD-SHELL, pg_isready]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - 9091:9091
    volumes:
      - ./config.yaml:/app/config.yaml
volumes:
  dbdata: {}
