version: "3.8"

services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=twfactor
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password@1
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [CMD-SHELL, pg_isready]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=passowrd101

  app:
    build: .
    ports:
      - 9091:9091
    command: ./srv server --config /app/config.yaml
    volumes:
      - ./config.yaml:/app/config.yaml
volumes:
  dbdata: {}
